services:
  api:
    build:
      context: ./project-lumen-source
      dockerfile: Dockerfile
    container_name: lumen-api
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./project-lumen-source:/app
    env_file: ./project-lumen-source/.env
    restart: unless-stopped
    networks:
      - lumen

networks:
  lumen:
    external: true
    name: lumen
